FROM python:3-alpine
# Allow statements and log messages to immediately appear in the Knative logs
ENV PYTHONUNBUFFERED True

ENV APP_HOME /app
WORKDIR $APP_HOME

# Install production dependencies.
RUN pip3 install Flask gunicorn music21==6.7.1 google-cloud-storage python-dotenv flask-cors
